# Lint対象から外すファイルのあるパスを記述
excluded:
  - vendor/bundle
  - Pods
  - Carthage
  - ./*/R.generated.swift

# 無効にするルール
disabled_rules:
  - trailing_whitespace
  - vertical_whitespace
  - unused_optional_binding
  - force_cast
  - force_try
  - file_length
  - line_length
  - type_body_length
  - function_body_length
  - empty_parentheses_with_trailing_closure

# 有効にするOpt-Inルール
opt_in_rules:
  # - force_unwrapping
  # - empty_count

